### ISSUE TITLE
control standard

### ISSUE THREAD

**Issue by dridk** [dridk/cutegl#5]
[ click + move ]                     => Tourne autour de l'object OK sauf bug #2 
[ click + move ] + ctrl            => Camera  z+ z- free 
[ click + move ] + shift          => Camera  y+ y- free 
[ click + move ] + ctrl + shift  => Rotation de la camera 

[ molette/gesture ]             =>  Camera z+ z-  by step
[ molette/gesture]  +  shift  =>  Camera y+ y- by step
[ molette/gesture]  +  ctrl    =>  Camera x+ x- by step

**Comment by yschutz** [comment]
> Le 7 sept. 2015 à 23:11, sacha schutz notifications@github.com a écrit :
> 
> [ click + move ]  => Tourne autour de l'object OK sauf bug #2 https://github.com/dridk/cutegl/issues/2 
> 
> corrigé
> [ click + move ] + ctrl => Camera z+ z- free
> 
> pageup/down fait ça 
> 
> [ click + move ] + shift => Camera y+ y- free
> 
> left/right fait ça et déplacement de la souris 
> 
> [ click + move ] + ctrl + shift => Rotation de la camera
> 
> click + déplacement de la souris fait ça
> [ molette/gesture ] => Camera z+ z- by step
> [ molette/gesture] + shift => Camera y+ y- by step
> [ molette/gesture] + ctrl => Camera x+ x- by step
> 
> j’ai pas de molette et gesture ne marche pas 
> —
> Reply to this email directly or view it on GitHub https://github.com/dridk/cutegl/issues/5.

# 

 Yves SCHUTZ (IN2P3-CNRS) collaboration ALICE
 Office: 301 01 022 GSM: +41 75 411 4755
 Mailbox: F02210    Tel: +41 22 76 72 131
 CERN               Fax: +41 22 76 79 480
 CH-1211 Genève 23  mél: schutz@in2p3.fr

**Comment by yschutz** [comment]
> [ molette/gesture ] => Camera z+ z- by step
> [ molette/gesture] + shift => Camera y+ y- by step
> [ molette/gesture] + alt    => Camera x+ x- by step

C’est fait

> —
> Reply to this email directly or view it on GitHub https://github.com/dridk/cutegl/issues/5.

# 

 Yves SCHUTZ (IN2P3-CNRS) collaboration ALICE
 Office: 301 01 022 GSM: +41 75 411 4755
 Mailbox: F02210    Tel: +41 22 76 72 131
 CERN               Fax: +41 22 76 79 480
 CH-1211 Genève 23  mél: schutz@in2p3.fr
